spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dlp
    username: dlp
    password: dlp
    driver-class-name: org.postgresql.Driver
    test-while-idle: true
    validation-query: SELECT

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true